#!/bin/bash
#NOM    : Demo
#CLASSE : IPC - LaboIPC 01-01
#OBJET  : réservé au makefile
#AUTEUR	: J.C. Jaumain, 07/2011

C='\033[44m'
E='\033[32m\033[1m'
N='\033[0m'
clear
echo -e "Exécution de ${E}ipcs -m${N}"
ipcs -m
echo -e "${C}             --> Enter pour continuer${N}"; read
echo "Démonstration des programmes AlloueShm.c et FreeShm.c"
echo "-----------------------------------------------------"
echo -e "Exécution de ${E}./AlloueShm&${N}"
./AlloueShm&
sleep 1
echo -e "${C}             --> Enter pour continuer${N}"; read
echo -e "Exécution de ${E}ipcs -m pour voir les mémoires allouées et l'état des attachements nattch${N}"
ipcs -m
echo -e "${C}             --> Enter pour continuer${N}"; read
echo -e "Exécution de ${E}./FreeShm${N} ceci peut prendre du temps ...."
./FreeShm
echo
echo -e "${C}             --> Enter pour continuer${N}"; read
echo -e "Exécution de ${E}ipcs -m${N}, seules les mémoires détachées sont libérées par free"
ipcs -m
echo -e "${C}             --> Enter pour continuer${N}"; read
echo -e "Exécution de ${E}killall AlloueShm${N} un détachement implicite de la mémoire sera fait"
killall AlloueShm
echo
echo -e "${C}             --> Enter pour continuer${N}"; read
echo -e "Exécution de ${E}ipcs -m${N}, les mémoire préalablement marquées pour suppression sont supprimées à leur tour lors du détachement implicite"
ipcs -m
echo -e "${C}             --> Enter pour continuer${N}"; read
