#NOM    : Makefile
#CLASSE : IPC - LaboIPC 02-01
#OBJET  : demo du programme Critique.c
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011

Synchro: Critique.c 
	gcc -std=c99 -D _GNU_SOURCE -Wall --pedantic-errors Critique.c -o Critique

clean:
	rm -f Critique *~

